[build]
  functions = "functions-build"
  command = "yarn build"
  publish = "build"
  
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'

[context.production]
  REACT_APP_API_ENDPOINT='https://trace-backend-prod.herokuapp.com'

[context.production.processing]
  skip_processing = false