[build]
  functions = "functions-build"
  command = "npm run build"
  publish = "public"
  
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'

[context.production]
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'

[context.production.processing]
  skip_processing = false
[context.production.processing.images]
  compress = false

[context.deploy-preview.processing]
  skip_processing = true
