[build]
  functions = "functions-build"
  command = "yarn build"
  publish = "build"
  
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'
  REACT_APP_FIRESTORE_PRODUCTS_DB_NAME='product-profiles-dev'
  REACT_APP_FIRESTORE_LOTS_DB_NAME='lots-dev'

[context.production]
  REACT_APP_API_ENDPOINT='https://trace-backend-prod.herokuapp.com'
  REACT_APP_FIRESTORE_PRODUCTS_DB_NAME='product-profiles'
  REACT_APP_FIRESTORE_LOTS_DB_NAME='lots'

[context.production.processing]
  skip_processing = false