[build]
  functions = "functions-build"
  command = "yarn run build"
  publish = "public"
  
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'

[context.production]
  REACT_APP_API_ENDPOINT='https://trace-backend-dev-pr-204.herokuapp.com'

[context.production.processing]
  skip_processing = false